#SPDX-License-Identifier: MIT-0
---
# tasks file for firewall
- ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- community.general.ufw:
    direction: incoming
    policy: deny

- community.general.ufw:
    direction: outgoing
    policy: allow

- community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- community.general.ufw:
    state: enabled
