#SPDX-License-Identifier: MIT-0
---
# tasks file for firewall
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Set the default incoming policy
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set the default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH traffic
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Enable the firewall
  community.general.ufw:
    state: enabled
