#SPDX-License-Identifier: MIT-0
---
# tasks file for tools
- name: Include Fastfetch tasks
  ansible.builtin.import_tasks: fastfetch.yml

- name: Include Neovim tasks
  ansible.builtin.import_tasks: neovim.yml

- name: Include Tree tasks
  ansible.builtin.import_tasks: tree.yml
