#SPDX-License-Identifier: MIT-0
---
# install and configure fail2ban
- ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
