#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh
- ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      X11Forwarding no
  notify: Restart ssh

- ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
