---
- hosts: all
  become: yes
  roles:
    - role: docker
      tags: [docker]

    - role: firewall
      tags: [firewall]

    - role: shell
      tags: [shell]

    - role: ssh
      tags: [ssh]

    - role: tools
      tags: [tools]
